# Site settings
title: "Nicholas Anthony"
email: "nic_960@hotmail.com"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/home/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
